---
AWSTemplateFormatVersion: "2010-09-09"
Description: Application Parameters
Parameters:
  ApplicationName:
    Type: String
    Description: Unique application/service name 
    Default: <Your app name>
  Host:
    Type: String
    Description: SMTP server Host
    Default: <Your smtp port>
  Port:
    Type: String
    Description: SMTP server port
    Default: 465
  
Resources:
    
  MailHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["", [!Ref ApplicationName, "-Host"]]
      Type: String
      Value: !Ref Host
  MailPort:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["", [!Ref ApplicationName, "-Port"]]
      Type: String
      Value: !Ref Port     
  SMTPSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join ["", [!Ref ApplicationName, "-SMTPSecret"]]
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "<UserName>"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: AppName
          Value: !Ref ApplicationName